### ISSUE TITLE
Correct Answer doesn't pass?

### ISSUE THREAD

**Issue by akedalat** [learn-co-curriculum/fewpjs-iterators-map-lab#6]
Hi, My solution to this lab is as follow: 

```js

function titleCased(){
  let result = []
  let toArr = tutorials.map(array => array.split(" "))
    for(let i = 0; i < toArr.length; i++){ 
      result[i] = (toArr[i].map(word => 
        word[0].toUpperCase() + word.slice(1))).join(" ")
    }
    return result
  }

```

which gives the following error:

```
 1) index.js
       titleCased()
         returns an array with title case tutorial names:
     AssertionError: expected [Function: titleCased] to be an array
      at Context.<anonymous> (test/indexTest.js:8:38)`
```
However when I copy and paste from the solution branch the test passes. 

Code from the solution branch: 

```js
  const titleCase = tutorials.map(function (tutorial) {
    tutorial = tutorial.split(' ');
    for (var i = 0; i < tutorial.length; i++) {
      tutorial[i] = tutorial[i].charAt(0).toUpperCase() + tutorial[i].slice(1);
    }
    return tutorial.join(' ');
  });
```

( I changed titleCased to titleCase to not receieve an already defined error from the console)

I tried the following tests in the console to prove that the result of my solution is identical to the solution branch:

```
Array.isArray(titleCased())
true
```

```
for(let i = 0; i < titleCase.length; i++){
titleCase[i] === titleCased()[i] 
console.log(i)
}
VM1585:3 0
VM1585:3 1
VM1585:3 2
VM1585:3 3
VM1585:3 4
VM1585:3 5
VM1585:3 6
VM1585:3 7
VM1585:3 8
VM1585:3 9
```

titleCase is a variable from the solution branch.
titleCased() is a function from my solution.

**Comment by sgharms** [comment]
Confirmed. There's a bug here. The second test expects that `titleCased` is an Array.

But the first test case says that `testCased()` is a function. We're only testing that it's a not `undefined`.

The tests need tightening to ensure that in the first test that titleCased exists ***and is a function***.

The solution has titleCased as a mere `Array`.

To the best I can tell, your code should work if things if things were configured correctly.

In your case, the test should be adjusted so that: 

```js
     it('returns an array with title case tutorial names', function () {
      expect(titleCased()).to.have.all.members(
```

In that case, your code works.

We'll fix.

**Comment by sgharms** [comment]
BTW: @akedalat 

Your use of GH markdown is really good. One thing you want to do when quoting code samples is to use "```(language)" to get line formatting and syntax highlighting. Single tick is good for setting off a `word` but to make your work look very professional, use that block highlight shortcut!

**Comment by drakeltheryuujin** [comment]
Hi @akedalat, 
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
